### PR TITLE
[Export] Add shim config for saveAs

### LINKED ISSUE #1821: [Export] saveAs is not a function
Following error appears on console when Export as JSON is invoked:

```
Uncaught (in promise) TypeError: this.saveAs is not a function
   at t.exportJSON (ExportService.js:80)
   at e.saveAs (ExportAsJSONAction.js:54)
   at e.<anonymous> (ExportAsJSONAction.js:94)
   at <anonymous>
```

Probably related to #1809

### PR DESCRIPTION
**Pull request by VWoeltjen**
Fixes #1821 after regression introduced by changing dependency in #1808. (The previous dependency fixed a [module naming issue](https://github.com/eligrey/FileSaver.js/issues/383), but got DMCA'd, so shim instead!)

### Author Checklist

1. Changes address original issue? Y
2. Unit tests included and/or updated with changes? N/A (changes at configuration level only)
3. Command line build passes? Y
4. Changes have been smoke-tested? Y

### CODE REVIEW

**Comment by dtailor90** [comment]
# Reviewer Checklist

Changes appear to address issue? Y
Appropriate unit tests included? N/A
Code style and in-line documentation are appropriate? N/A
Commit messages meet standards? Y
